# Generated by Django 4.2.16 on 2024-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentManagementAppointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'appointment_management_appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('referee_id', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('weekday', models.CharField(blank=True, max_length=3, null=True)),
                ('availabletype', models.CharField(db_column='availableType', max_length=1)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('availableid', models.AutoField(db_column='availableID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(db_column='club_ID', max_length=50, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(db_column='match_ID', max_length=50, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('level', models.CharField(max_length=50)),
                ('match_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preference_id', models.AutoField(db_column='preference_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Preference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('referee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Referee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('relative_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('relative_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Relative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.CharField(db_column='venue_ID', max_length=50, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Venue',
                'managed': False,
            },
        ),
    ]
