# Generated by Django 4.2.16 on 2024-10-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="relative", name="id",),
        migrations.AlterField(
            model_name="relative",
            name="referee",
            field=models.ForeignKey(
                db_column="referee_ID",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="appointment_management.referee",
            ),
        ),
    ]
