# Generated by Django 4.2.16 on 2024-10-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0002_appointmentmanagementappointment_authgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='relative',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': True},
        ),
    ]
